only_for_countries = {
 'AIA':'Anguilla',
 'ATG':'Antigua and Barbuda',
 'ABW':'Aruba',
 'BHS':'Bahamas',
 'BRB':'Barbados',
 'BLZ':'Belize',
 '':'Bonaire',
 'VGB':'British Virgin Islands',
 'GTM':'Guatemala',
 'GLP':'Guadeloupe',
 'GUY':'Guyana',
 'GUF':'French Guiana',
 'CYM':'Cayman Islands',
 'COL':'Colombia',
 'CRI':'Costa Rica',
 'CUB':'Cuba',
 '':'Curaçao',
 'DMA':'Dominica',
 'DOM':'Dominican Republic',
 'GRD':'Grenada',
 'HTI':'Haiti',
 'HND':'Honduras',
 'JAM':'Jamaica',
 'MTQ':'Martinique',
 'MEX':'Mexico',
 'MSR':'Montserrat',
 'NIC':'Nicaragua',
 'PAN':'Panama',
 'PRI':'Puerto Rico',
 'BLM':'Saint-Barthélemy',
 'MAF':'Saint-Martin',
 '':'Saint Maarten',
 'KNA':'Saint Kitts and Nevis',
 'LCA':'Saint Lucia',
 'VCT':'Saint Vincent and the Grenadines',
 '':'Saint Eustatius and Saba',
 'SUR':'Suriname',
 'TCA':'Turks and Caicos Islands',
 'TTO':'Trinidad and Tobago',
 'USA':'United States',
 'VIR':'Virgin Islands',
 'VEN':'Venezuela',
}