#!/bin/bash

scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2010_01.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2010_02.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2010_03.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2010_04.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2010_05.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2010_06.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2010_07.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2010_08.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2010_09.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2010_10.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2010_11.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2010_12.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2011_01.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2011_02.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2011_03.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2011_04.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2011_05.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2011_06.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2011_07.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2011_08.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2011_09.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2011_10.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2011_11.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2011_12.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2012_01.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2012_02.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2012_03.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2012_04.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2012_05.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2012_06.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2012_07.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2012_08.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2012_09.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2012_10.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2012_11.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2012_12.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2013_01.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2013_02.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2013_03.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2013_04.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2013_05.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2013_06.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2013_07.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2013_08.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2013_09.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2013_10.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2013_11.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2013_12.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2014_01.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2014_02.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2014_03.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2014_04.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2014_05.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2014_06.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2014_07.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2014_08.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2014_09.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2014_10.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2014_11.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2014_12.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2015_01.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2015_02.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2015_03.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2015_04.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2015_05.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2015_06.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2015_07.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2015_08.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2015_09.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2015_10.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2015_11.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2015_12.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2016_01.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2016_02.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2016_03.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2016_04.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2016_05.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2016_06.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2016_07.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2016_08.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2016_09.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2016_10.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2016_11.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2016_12.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2017_01.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2017_02.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2017_03.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2017_04.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2017_05.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2017_06.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2017_07.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2017_08.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2017_09.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2017_10.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2017_11.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2017_12.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2018_01.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2018_02.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2018_03.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2018_04.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2018_05.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2018_06.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2018_07.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2018_08.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2018_09.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2018_10.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2018_11.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2018_12.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2019_01.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2019_02.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2019_03.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2019_04.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2019_05.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2019_06.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2019_07.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2019_08.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2019_09.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2019_10.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2019_11.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
scp -r /data/UN_Litter_data/output/TEN_YEARS/YesWinds_YesDiffusion_NoUnbeaching/TenYears_YesWinds_YesDiffusion_NoUnbeaching_2019_12.nc osz09@coaps.rcc.fsu.edu:~/scratch/TEN_YEARS/
